spring:
  application:
    name: consumer-80-feign-hystrix
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
server:
  port: 80

feign:
  hystrix:
    enabled: true

