server:
  port: 9527

spring:
  application:
    name: gateway-9587
#  cloud:
#    gateway:
#      routes:
#        - id: route_provider123123 #随便起
#          uri: lb://provider # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
#          predicates:
#            - Path=/abc/get/**
#          filters:
#            - StripPrefix=1 # 表示在转发时去掉path中的abc
#            #- PrefixPath=/mypath #在URL路径前面添加一部分的前缀

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
