spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:7001
server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
