server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  #ignored-services: microservicecloud-dept  #忽略某一个名称不能访问，只能用映射的名称访问
  ignored-services: "*"
  prefix: /abc          #设置公共前缀
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**


info:
  app.name: abc-microcloud
  company.name: defg



